//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="d", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceOMG")]
    [System.SerializableAttribute()]
    public partial class d : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dear {
            get {
                return this.DearField;
            }
            set {
                if ((object.ReferenceEquals(this.DearField, value) != true)) {
                    this.DearField = value;
                    this.RaisePropertyChanged("Dear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOdataCollectionByAuthByHttpExample", ReplyAction="http://tempuri.org/IService1/GetOdataCollectionByAuthByHttpExampleResponse")]
        WebApplication8.Service.d[] GetOdataCollectionByAuthByHttpExample(int posision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOdataCollectionByAuthByHttpExample", ReplyAction="http://tempuri.org/IService1/GetOdataCollectionByAuthByHttpExampleResponse")]
        System.Threading.Tasks.Task<WebApplication8.Service.d[]> GetOdataCollectionByAuthByHttpExampleAsync(int posision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateBpmEntityByOdataHttpExample", ReplyAction="http://tempuri.org/IService1/CreateBpmEntityByOdataHttpExampleResponse")]
        void CreateBpmEntityByOdataHttpExample(string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateBpmEntityByOdataHttpExample", ReplyAction="http://tempuri.org/IService1/CreateBpmEntityByOdataHttpExampleResponse")]
        System.Threading.Tasks.Task CreateBpmEntityByOdataHttpExampleAsync(string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateExistingBpmEnyityByOdataHttpExample", ReplyAction="http://tempuri.org/IService1/UpdateExistingBpmEnyityByOdataHttpExampleResponse")]
        void UpdateExistingBpmEnyityByOdataHttpExample(string Id, string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateExistingBpmEnyityByOdataHttpExample", ReplyAction="http://tempuri.org/IService1/UpdateExistingBpmEnyityByOdataHttpExampleResponse")]
        System.Threading.Tasks.Task UpdateExistingBpmEnyityByOdataHttpExampleAsync(string Id, string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBpmEntityByOdataHttpExample", ReplyAction="http://tempuri.org/IService1/DeleteBpmEntityByOdataHttpExampleResponse")]
        bool DeleteBpmEntityByOdataHttpExample(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBpmEntityByOdataHttpExample", ReplyAction="http://tempuri.org/IService1/DeleteBpmEntityByOdataHttpExampleResponse")]
        System.Threading.Tasks.Task<bool> DeleteBpmEntityByOdataHttpExampleAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication8.Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication8.Service.IService1>, WebApplication8.Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication8.Service.d[] GetOdataCollectionByAuthByHttpExample(int posision) {
            return base.Channel.GetOdataCollectionByAuthByHttpExample(posision);
        }
        
        public System.Threading.Tasks.Task<WebApplication8.Service.d[]> GetOdataCollectionByAuthByHttpExampleAsync(int posision) {
            return base.Channel.GetOdataCollectionByAuthByHttpExampleAsync(posision);
        }
        
        public void CreateBpmEntityByOdataHttpExample(string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate) {
            base.Channel.CreateBpmEntityByOdataHttpExample(Name, MobilePhone, Dear, JobTitle, BirthDate);
        }
        
        public System.Threading.Tasks.Task CreateBpmEntityByOdataHttpExampleAsync(string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate) {
            return base.Channel.CreateBpmEntityByOdataHttpExampleAsync(Name, MobilePhone, Dear, JobTitle, BirthDate);
        }
        
        public void UpdateExistingBpmEnyityByOdataHttpExample(string Id, string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate) {
            base.Channel.UpdateExistingBpmEnyityByOdataHttpExample(Id, Name, MobilePhone, Dear, JobTitle, BirthDate);
        }
        
        public System.Threading.Tasks.Task UpdateExistingBpmEnyityByOdataHttpExampleAsync(string Id, string Name, string MobilePhone, string Dear, string JobTitle, System.DateTime BirthDate) {
            return base.Channel.UpdateExistingBpmEnyityByOdataHttpExampleAsync(Id, Name, MobilePhone, Dear, JobTitle, BirthDate);
        }
        
        public bool DeleteBpmEntityByOdataHttpExample(string Id) {
            return base.Channel.DeleteBpmEntityByOdataHttpExample(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBpmEntityByOdataHttpExampleAsync(string Id) {
            return base.Channel.DeleteBpmEntityByOdataHttpExampleAsync(Id);
        }
    }
}
